SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS stockkeepunits;

DROP TABLE IF EXISTS recipe_input_sku;
DROP TABLE IF EXISTS recipe_output_sku;
DROP TABLE IF EXISTS recipe_toolreq_sku;
SET FOREIGN_KEY_CHECKS = 1;